// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace win21
{
    public partial class Post
    {
        [Key]
        public int Id { get; set; }
        public string PostName { get; set; }
        public DateTime? UploadDate { get; set; }
        public string PostUrl { get; set; }
        public string PostSize { get; set; }
        public string UserId { get; set; }
        //public IdentityUser User { get; set; }
    }
}